CREATE TABLE [dbo].[Player]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [Name] NVARCHAR(50) NOT NULL DEFAULT '', 
    [IsMachine] BIT NOT NULL DEFAULT 0, 
    [GamePieceId] UNIQUEIDENTIFIER NULL
)
